@PaliTravel_HostAddress = http://localhost:5245

POST {{PaliTravel_HostAddress}}/signup
Accept: application/json

###

POST {{PaliTravel_HostAddress}}/login
Accept: application/json

###

POST {{PaliTravel_HostAddress}}/city
Accept: application/json

###

POST {{PaliTravel_HostAddress}}/hotel
Accept: application/json
